name: Update submodules

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  Update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Pull
        run: |
          git submodule update  --init --recursive --remote -f

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.repository == 'pinanek/catppina' && github.ref == 'refs/heads/main' }}
        with:
          commit_message: "chore: Pull the latest changes for port(s)"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: ${{ github.head_ref }}
